name: Run Playwright tests

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  all-checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["20"]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Save CI session storage state
        run: echo "${{ secrets.CI_STORAGE_STATE }}" | base64 --decode > storageState.json

      - name: Run checks and tests
        run: |
          npm run biome:fix
          npm run build
          npx playwright install --with-deps
          npx playwright test
        env:
          CI: true
          LOCAL_URL: "http://localhost:3000"
          PRODUCTION_URL: ${{ secrets.PRODUCTION_URL }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          TURSO_AUTH_TOKEN: ${{ secrets.TURSO_AUTH_TOKEN }}
          TURSO_CONNECTION_URL: ${{ secrets.TURSO_CONNECTION_URL }}
          NEXT_PUBLIC_SENTRY_DSN: ${{ secrets.NEXT_PUBLIC_SENTRY_DSN }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

      - name: Upload playwright reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-reports
          path: playwright-report/
          retention-days: 7
